version: "3.8"

services:
  front:
    build:
      context: ./front
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true

  back:
    build:
      context: ./back
    volumes:
      - ./back:/app
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
